[package]
name = "Rust"
version = "0.1.0"
authors = ["lilBunnyRabbit <andrazcollege@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
serenity = "0.8"
dotenv = "0.15.0"